# -*- coding: utf-8 -*-
"""Campaña Marketing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pj6GUFumzCeR_IJKOt8hpKuoC_pnmOaI
"""



"""# Campaña Maarketing

### **Actividades Principales:**
1. Identificación y tratamiento de valores perdidos.
2. Identificación y tratamiento de valores atípicos.
3. Cálculo de medidas estadísticas clave.
4. Visualización de la distribución y relaciones entre variables.
5. Documentación y análisis final.

---

## Definición del alcance del proyecto

- Vamos a analizar el conjunto de datos para descartar información irrelevante, identificar patrones, realizar análisis estadísticos y generar percepciones.

 - La meta final es brindar propuestas cuantitativas con el objetivo de mejorar la eficacia en, por lo menos, un 12%.

## 1. Cargar el Dataset y Realizar una Exploración Inicial
"""

## Se importa las bibliotecas para el desarrollo del proyecto

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Cargo los datos # Metodo 1:

df_csv = pd.read_csv("Marketing.csv", sep=';')

## Ver la tabla
df_csv

## 5 métodos de Pandas para transformar y limpiar 5 de las columnas del dataset.

## HEAD para ver las primeras filas

print(df_csv.head())

# El archivo no especifica 'Duration'. Asi que la cantidas de 3 cifras lo reflejo x seg.

## Metodo 2: Renombraré la columna 'Duration' por 'Duration*Min'

df_csv = df_csv.rename(columns={'duration': 'duration*min'})

## Acceder a la columna 'duration*min'
df_csv['duration*min']

## Metodo 3: Transformar de segundos a minutos
df_csv['duration*min'] = df_csv['duration*min'] / 60
df_csv['duration*min'] = df_csv['duration*min'].round(2)
df_csv['duration*min']

# Metodo 4:  Agrupar por 'poutcome' y calcular el conteo promedio de 'campaign
media = df_csv.groupby('poutcome')['campaign'].mean().reset_index()  # Agrupa y calcula media
print("\nMedia de 'campaign' por 'poutcome':")
print(media)

## Metodo 5: Limpiar datos con espacio
df_csv['education'] = df_csv['education'].astype(str).str.strip()
print(df_csv['education'].unique())

"""## 2. Tratamiento de Valores Perdidos

#### Identificación de Valores Perdidos
"""

## Identificación de Valores Perdidos
print("Valores 'unknown' por columna:")
print((df_csv == 'unknown').sum())

# Mostrar el porcentaje de valores perdidos
print("Porcentaje de valores 'unknown' por columna:")
print((df_csv == 'unknown').mean()*100)

"""#### Tratamiento de valores perdidos"""

## Eliminar filas con valores perdidos
print("Eliminando filas con valores perdidos")
print(df_csv.dropna()) # No cumple la funcion porque los valores perdidos

# Cuenta 'unknown' en categóricas
print("\n'Unknown' en categóricas:")
for col in ['job', 'education', 'default', 'housing', 'loan']:
    print(f"{col}: {(df_csv[col] == 'unknown').sum()}")

# Paso 2: Tratamiento simple
# Rellena numéricas con mediana
df_csv['age'] = df_csv['age'].fillna(df_csv['age'].median())
df_csv['duration*min'] = df_csv['duration*min'].fillna(df_csv['duration*min'].median())
df_csv['campaign'] = df_csv['campaign'].fillna(df_csv['campaign'].median())
# Removed 'pdays' as it was dropped in a previous cell
# Removed 'previous' as it was dropped in a previous cell

# Rellena categóricas con moda
df_csv['job'] = df_csv['job'].replace('unknown', df_csv['job'].mode()[0])
df_csv['education'] = df_csv['education'].replace('unknown', df_csv['education'].mode()[0])
df_csv['default'] = df_csv['default'].replace('unknown', df_csv['default'].mode()[0])
df_csv['housing'] = df_csv['housing'].replace('unknown', df_csv['housing'].mode()[0])
df_csv['loan'] = df_csv['loan'].replace('unknown', df_csv['loan'].mode()[0])


# Eliminación de filas
df_csv = df_csv.dropna(thresh=0.95 * len(df_csv.columns))  # Filas con 95% completas

#  Verificación
print("\nDespués del tratamiento:")
print(df_csv.isnull().sum())  # Confirma limpieza
print(df_csv.head())

"""## 3. Identificación y Tratamiento de Valores Atípicos"""

## Identificación y Tratamiento de Valores Atípicos

## Numero de valores atipicos en "duration"
cuartiles = df_csv['duration*min'].quantile([0.25, 0.75])
print("Los valores atipicos son:")
print(cuartiles)

## Numero de valores atipicos en "duration"
cuartiles = df_csv['cons.conf.idx'].quantile([0.25, 0.75])
print("Los valores atipicos son:")
print(cuartiles)

# Identificación de valores atípicos en 'duration' usando IQR

Q1 = df_csv['cons.conf.idx'].quantile(0.25)
Q3 = df_csv['cons.conf.idx'].quantile(0.75)
IQR = Q3 - Q1
atipicos = df_csv[(df_csv['cons.conf.idx'] < (Q1 - 1.5 * IQR)) | (df_csv['cons.conf.idx'] > (Q3 + 1.5 * IQR))]
print(f"\nNúmero de valores atípicos en 'cons.conf.idx': {len(atipicos)}")

"""## 4. Cálculo de Medidas Estadísticas"""

## Analisis Estadistico

## Calculo para las columnas "AGE"

print ("\nMedidas de tendencia central y disperción para 'age':")
media = df_csv['age'].mean().astype(int)
mediana = df_csv['age'].median()
moda = df_csv['age'].mode()[0]
desviacion_estandar = df_csv['age'].std()
varianza = df_csv['age'].var()
coef_var = (desviacion_estandar / media) * 100


print(f"Media es:{media:.2f}")
print(f"Mediana es:{mediana:.2f}")
print(f"Moda es:{moda}")
print(f"Desviacion estandar es:{desviacion_estandar:.2f}")
print(f"Varianza es:{varianza:.2f}")
print(f"Coeficiente es:{coef_var:.2f}%")

## Calculo para las columnas "duration"

print ("\nMedidas de tendencia central y disperción para 'duration':")
media = df_csv['duration*min'].mean().astype(int)
mediana = df_csv['duration*min'].median()
moda = df_csv['duration*min'].mode()[0]
desviacion_estandar = df_csv['duration*min'].std()
varianza = df_csv['duration*min'].var()
coef_var = (desviacion_estandar / media) * 100


print(f"Media es:{media:.1f}")
print(f"Mediana es:{mediana:.1f}")
print(f"Moda es:{moda}")
print(f"Desviacion estandar es:{desviacion_estandar:.1f}")
print(f"Varianza es:{varianza:.1f}")
print(f"Coeficiente es:{coef_var:.1f}%")

def calculo_estadistico(df_csv):

    resultado = []
    for columna in df_csv.columns:
        moda = df_csv[columna].mode().iloc[0] if not df_csv[columna].mode().empty else None

        if pd.api.types.is_numeric_dtype(df_csv[columna]):
            # Calcular mediana
            mediana = df_csv[columna].median()
            # Calcular desviación estándar
            Des_sta = ((df_csv[columna].var())**0.5)
            # Calcular media
            media = df_csv[columna].mean()
            # Calcular coeficiente de variación (CV)
            if media != 0:
                CV = (Des_sta / media) * 100
            else:
                CV = None
        else:
            Des_sta = None
            CV = None

        resultado.append({'columna': columna, 'moda': moda, 'media': media, 'mediana': mediana, 'Desviacion estandar': Des_sta, 'Coeficiente de variacion': CV})

    df_resultado = pd.DataFrame(resultado)
    return df_resultado

calculo_estadistico(df_csv)

"""## 5. Visualización de la Distribución de las Variables"""

## Visualización de la Distribución de las Variables

## Grafico 1: Variable numerico para AGE
sns.set_style("whitegrid")
plt.figure(figsize=(8,5))
sns.histplot(df_csv['age'], bins=20, kde=True, color='blue', alpha =0.7) ## Histograma KDE para ver la distribucion

plt.title('Distribución de la Edad')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()

## Grafico 2: Visualización de outliers boxplot para la duración de llamadas
plt.figure(figsize=(8,4))
sns.boxplot(x='y', y='duration*min', data=df_csv, palette='Set1')  # Boxplot para duración por aceptación
plt.title('Boxplot: Duración de Llamadas por Aceptación')
plt.xlabel('Aceptación (y)')
plt.ylabel('Duración (minutos)')
plt.show()

## Grafico 3: Visualización de "job" 0
plt.figure(figsize=(8,4))
sns.countplot(y='job', data=df_csv, order=df_csv['job'].value_counts().index, palette='viridis')  # Barras horizontales
plt.title('Count Plot: Frecuencia de Tipos de Trabajo')
plt.xlabel('Frecuencia')
plt.ylabel('Tipo de Trabajo')
plt.show()

## Grafico 4:  Scatterplot, relación de "AGE" y "CAMPAIGN"
plt.figure(figsize=(8,4))
sns.scatterplot(x='age', y='campaign', hue='y', data=df_csv, palette='coolwarm')  # Scatter con color por categoría
plt.title('Scatter Plot: Edad vs. Número de Contactos')
plt.xlabel('Edad')
plt.ylabel('Numero de campaña')
plt.legend(title='Aceptación')
plt.show()

## Grafico 5: Visualización de Tasa de Empleo por Resultado de campaña
plt.figure(figsize=(8, 6))
sns.boxplot(data=df_csv, x='y', y='emp.var.rate', palette ='Set2')
plt.title('Boxplot de Tasa de Empleo por Resultado de Campaña', fontsize=14)
plt.xlabel('Tasa de variación del empleo')
plt.ylabel('Resultado de campaña')
plt.show()

plt.figure(figsize=(8,4))
sns.violinplot(x='marital', y='duration*min', data=df_csv, palette='muted')  # Violin para densidad
plt.title('Violin Plot: Distribución de Duración por Estado Civil')
plt.xlabel('Estado Civil')
plt.ylabel('Duración')
plt.show()

plt.figure(figsize=(8, 6))
corr_matrix = df_csv.corr(numeric_only=True)  # Heatmap de correlación
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Matriz de Correlación de Variables Numéricas')
plt.show()

# Se guarda la nueva data procesado
df_csv.to_csv('BankMarketing_Actualizado.csv', index=False)

"""## Generación de Insights

######
- Los usuarios clientes estan entre los 27-45 años lo cual estan dentro de una distribución positiva y se sugiere que las campañas deben maximizar su efectividad aumentando la tasa de aceptación a un 10%

- La supresión de filas con muchos valores ausentes disminuye el conjunto de datos en menos del 5%, pero garantiza la calidad sin que se pierda información esencial.

- Según análisis anteriores del conjunto de datos, los clientes cuyo trabajo es 'admin' presentan una tasa de aceptación ('yes') de aproximadamente el 10%, en contraste con la tasa del 15% que tienen los clientes con 'management'.  La razón por la que el KPI de efectividad es bajo se debe parcialmente a que 'admin' predomina en el conjunto de datos: la mayor parte de los contactos se encuentra en segmentos con escasa conversión.

- La variable "duration" indica que las llamadas más extensas tienen una mejor tasa de aceptación, lo cual explica el motivo por el que las campañas breves contribuyen a una baja efectividad (8%).  Las variables económicas correlacionadas indican que los períodos en que la 'emp.var.rate' (tasa de variación del empleo) es elevada pueden disminuir la aceptación, pues señalan inestabilidad económica.

- El mapa de calor revela ciertas correlaciones entre las variables numéricas. Estas variables también están negativamente correlacionadas con previous y pdays. Esto indica que los resultados de campañas previas y las variables macroeconómicas están vinculadas entre sí y tienen el potencial de afectar la efectividad de la campaña.
"""

